# Property of Levelfly. All rights reserved.
# This script is generated by script/create_wardrobe.rb on 2014-11-12

task :load_wardrobe => :environment do

  Reward.delete_all("target_type = 'wardrobe'")
  WardrobeItem.delete_all("depth = 2 and item_type <> 'head' and item_type <> 'hair'")
  Wardrobe.delete_all("name <> 'Basic'")

  # === Basic ===
  Wardrobe.unlock_lvl('Basic', 1)
  Wardrobe.add('Basic', 'Accessories', 'Jewelry', 'Hoop Earrings', 'earrings', 'basic/earrings/earring_large_ring', 0)
  Wardrobe.add('Basic', 'Accessories', 'Jewelry', 'Pearl Earrings', 'earrings', 'basic/earrings/earring_white', 1)
  Wardrobe.add('Basic', 'Accessories', 'Misc', 'Gray Gloves', 'prop', 'basic/glove/glove_gray', 0)
  Wardrobe.add('Basic', 'Accessories', 'Misc', 'Pink Teddy Bear', 'prop', 'basic/props/pink_teddy', 1)
  Wardrobe.add('Basic', 'Accessories', 'Bags', 'Handbag', 'prop', 'basic/props/hand_bag', 0)
  Wardrobe.add('Basic', 'Body', 'Casual', 'Short Buttoned Blue Shirt', 'top', 'basic/tops/shirt_short_sleeve_cyan', 0, 'Blue Button Up')
  Wardrobe.add('Basic', 'Body', 'Casual', 'Short Buttoned Pink Shirt', 'top', 'basic/tops/shirt_short_sleeve_pink', 1, 'Pink Button Up')
  Wardrobe.add('Basic', 'Head', 'Face', 'Face 9', 'face', 'basic/expression/angry_1', 0)
  Wardrobe.add('Basic', 'Head', 'Face', 'Face 10', 'face', 'basic/expression/angry_2', 1)
  Wardrobe.add('Basic', 'Head', 'Face', 'Face 11', 'face', 'basic/expression/angry_3', 2)
  Wardrobe.add('Basic', 'Head', 'Face', 'Face 12', 'face', 'basic/expression/angry_4', 3)
  Wardrobe.add('Basic', 'Head', 'Face', 'Face 13', 'face', 'basic/expression/smile_1', 4)
  Wardrobe.add('Basic', 'Head', 'Face', 'Face 14', 'face', 'basic/expression/smile_2', 5)
  Wardrobe.add('Basic', 'Head', 'Face', 'Face 15', 'face', 'basic/expression/smile_3', 6)
  Wardrobe.add('Basic', 'Head', 'Face', 'Face 16', 'face', 'basic/expression/smile_4', 7)
  Wardrobe.add('Basic', 'Head', 'Face', 'Face 17', 'face', 'basic/expression/winking_1', 8)
  Wardrobe.add('Basic', 'Head', 'Face', 'Face 18', 'face', 'basic/expression/winking_2', 9)
  Wardrobe.add('Basic', 'Head', 'Face', 'Face 19', 'face', 'basic/expression/winking_3', 10)
  Wardrobe.add('Basic', 'Head', 'Face', 'Face 20', 'face', 'basic/expression/winking_4', 11)
  Wardrobe.add('Basic', 'Head', 'Facial Hair', 'Handlebar', 'facial_hair', 'basic/facial_hair/handlebar_chin_puff_4', 0)
  Wardrobe.add('Basic', 'Head', 'Facial Hair', 'La Sauvarov', 'facial_hair', 'basic/facial_hair/la_souvarov_4', 1)
  Wardrobe.add('Basic', 'Head', 'Facial Hair', 'Balbo', 'facial_hair', 'basic/facial_hair/balbo_4', 2)
  Wardrobe.add('Basic', 'Head', 'Facial Hair', 'Chin Curtain', 'facial_hair', 'basic/facial_hair/chin_curtain_4', 3)
  Wardrobe.add('Basic', 'Head', 'Facial Hair', 'French Fork', 'facial_hair', 'basic/facial_hair/french_fork_4', 4)
  Wardrobe.add('Basic', 'Head', 'Facial Hair', 'Friendly Mutton Chop', 'facial_hair', 'basic/facial_hair/friendily_mutton_chop_4', 5)
  Wardrobe.add('Basic', 'Head', 'Facial Hair', 'Goatee', 'facial_hair', 'basic/facial_hair/goatee_4', 6)
  Wardrobe.add('Basic', 'Head', 'Facial Hair', 'Holywoodian', 'facial_hair', 'basic/facial_hair/hollywoodian_4', 7)
  Wardrobe.add('Basic', 'Head', 'Facial Hair', 'Hulihee', 'facial_hair', 'basic/facial_hair/hulihee_4', 8)
  Wardrobe.add('Basic', 'Head', 'Facial Hair', 'Mustache Goatee', 'facial_hair', 'basic/facial_hair/mustache_goatee_4', 9)
  Wardrobe.add('Basic', 'Head', 'Facial Hair', 'Mutton Chop', 'facial_hair', 'basic/facial_hair/mutton_chop_4', 10)
  Wardrobe.add('Basic', 'Head', 'Facial Hair', 'Santa', 'facial_hair', 'basic/facial_hair/santa_facial_hair_4', 11)
  Wardrobe.add('Basic', 'Head', 'Facial Hair', 'Short Boxed Beard', 'facial_hair', 'basic/facial_hair/short_boxed_beard_4', 12)
  Wardrobe.add('Basic', 'Head', 'Facial Hair', 'Short Mustache', 'facial_hair', 'basic/facial_hair/short_mustache_4', 13)
  Wardrobe.add('Basic', 'Head', 'Facial Hair', 'Sideburns Long', 'facial_hair', 'basic/facial_hair/sideburns_long_4', 14)
  Wardrobe.add('Basic', 'Head', 'Facial Hair', 'Sideburns Short', 'facial_hair', 'basic/facial_hair/sideburns_short_4', 15)
  Wardrobe.add('Basic', 'Head', 'Facial Hair', 'Van Dyke', 'facial_hair', 'basic/facial_hair/van_dyke_4', 16)
  Wardrobe.add('Basic', 'Legs', 'Casual', 'Black Skinny Jeans', 'bottom', 'basic/bottoms/black_tight_jean', 0)

  # === BMCC T-shirts ===
  Wardrobe.unlock_lvl('BMCC T-shirts', 2)
  Wardrobe.add('BMCC T-shirts', 'Body', 'Casual', 'BMCC 1', 'top', 'bmcc_t-shirts/tops/bmcc_blue', 2)
  Wardrobe.add('BMCC T-shirts', 'Body', 'Casual', 'BMCC 2', 'top', 'bmcc_t-shirts/tops/bmcc_light_gray', 3)
  Wardrobe.add('BMCC T-shirts', 'Body', 'Casual', 'BMCC 3', 'top', 'bmcc_t-shirts/tops/bmcc_small_logo', 4)
  Wardrobe.add('BMCC T-shirts', 'Body', 'Casual', 'BMCC 4', 'top', 'bmcc_t-shirts/tops/bmcc_yellow_small_logo', 5)

  # === Basketball Uniform ===
  Wardrobe.unlock_lvl('Basketball Uniform', 3)
  Wardrobe.add('Basketball Uniform', 'Body', 'Sporty', 'Basketball Jersey', 'top', 'basketball_uniform/tops/basketball_t_shirt', 0)
  Wardrobe.add('Basketball Uniform', 'Feet', 'Sporty', 'Basketball Shoes', 'shoes', 'basketball_uniform/shoes/basketball_shoe', 0)
  Wardrobe.add('Basketball Uniform', 'Legs', 'Sporty', 'Basketball Shorts', 'bottom', 'basketball_uniform/bottoms/basketball_short', 0)
  Wardrobe.add('Basketball Uniform', 'Accessories', 'Misc', 'Sunglasses', 'prop', 'basketball_uniform/glasses/shade_black', 2)

  # === Cowboy Outfit ===
  Wardrobe.unlock_lvl('Cowboy Outfit', 6)
  Wardrobe.add('Cowboy Outfit', 'Body', 'Misc', 'Cowboy Vest', 'top', 'cowboy_outfit/tops/cowboy_top_without_court', 0)
  Wardrobe.add('Cowboy Outfit', 'Legs', 'Misc', 'Cowboy Chaps', 'bottom', 'cowboy_outfit/bottoms/cowboy_bottom', 0)

  # === Skater Accessories ===
  Wardrobe.unlock_lvl('Skater Accessories', 7)
  Wardrobe.add('Skater Accessories', 'Accessories', 'Hobbies', 'Skateboard', 'prop', 'skater_accessories/props/skateboard', 0)

  # === Doctor Accessories ===
  Wardrobe.unlock_lvl('Doctor Accessories', 8)
  Wardrobe.add('Doctor Accessories', 'Accessories', 'Misc', 'Stethoscope', 'prop', 'doctor_accessories/props/stethoscope', 3)

  # === Business Outfits ===
  Wardrobe.unlock_lvl('Business Outfits', 9)
  Wardrobe.add('Business Outfits', 'Body', 'Dressy', 'Red Tie', 'top', 'business_outfits/tops/red_tie_shirt_long_sleeve', 0)
  Wardrobe.add('Business Outfits', 'Body', 'Dressy', 'Argyle Sweater', 'top', 'business_outfits/tops/shirt_long_sleeve_with_jacket', 1)
  Wardrobe.add('Business Outfits', 'Body', 'Dressy', 'Blue Tie', 'top', 'business_outfits/tops/tie_shirt_long_sleeve_yellow', 2)
  Wardrobe.add('Business Outfits', 'Legs', 'Dressy', 'Brown Trousers', 'bottom', 'business_outfits/bottoms/trousers_long_brown', 0)

  # === Army Uniform ===
  Wardrobe.unlock_lvl('Army Uniform', 10)
  Wardrobe.add('Army Uniform', 'Body', 'Career', 'Army Shirt 1', 'top', 'army_uniform/tops/shirt_army', 0)
  Wardrobe.add('Army Uniform', 'Body', 'Career', 'Army Shirt 2', 'top', 'army_uniform/tops/t_shirt_army', 1)

  # === New Jewelry ===
  Wardrobe.unlock_lvl('New Jewelry', 11)
  Wardrobe.add('New Jewelry', 'Accessories', 'Jewelry', 'Sapphire Earrings', 'earrings', 'new_jewelry/earrings/earring_blue', 2)
  Wardrobe.add('New Jewelry', 'Accessories', 'Jewelry', 'Ruby Earrings', 'earrings', 'new_jewelry/earrings/earring_red', 3)
  Wardrobe.add('New Jewelry', 'Accessories', 'Jewelry', 'Silver Drop Earrings', 'earrings', 'new_jewelry/earrings/earring_silver_1', 4)
  Wardrobe.add('New Jewelry', 'Accessories', 'Jewelry', 'Silver Stud Earrings', 'earrings', 'new_jewelry/earrings/earring_silver_2', 5)
  Wardrobe.add('New Jewelry', 'Accessories', 'Jewelry', 'Silver Necklace 1', 'necklace', 'new_jewelry/necklace/necklace_silver_1', 6)
  Wardrobe.add('New Jewelry', 'Accessories', 'Jewelry', 'Silver Necklace 2', 'necklace', 'new_jewelry/necklace/necklace_silver_2', 7)
  Wardrobe.add('New Jewelry', 'Accessories', 'Jewelry', 'Diamond Necklace 1', 'necklace', 'new_jewelry/necklace/necklace_diamond_1', 8)
  Wardrobe.add('New Jewelry', 'Accessories', 'Jewelry', 'Diamond Necklace 2', 'necklace', 'new_jewelry/necklace/necklace_diamond_2', 9)

  # === Pirate Costume ===
  Wardrobe.unlock_lvl('Pirate Costume', 12)
  Wardrobe.add('Pirate Costume', 'Legs', 'Misc', 'Pirate Bottom', 'bottom', 'pirate_costume/bottoms/pirate_bottom', 1)
  Wardrobe.add('Pirate Costume', 'Feet', 'Misc', 'Pirate Boots', 'shoes', 'pirate_costume/shoes/pirate_boot', 0)
  Wardrobe.add('Pirate Costume', 'Body', 'Misc', 'Pirate Top', 'top', 'pirate_costume/tops/pirate_top', 1)
  Wardrobe.add('Pirate Costume', 'Head', 'Misc', 'Pirate Hat 2', 'hat', 'pirate_costume/hats/pirate_hat', 0)

  # === New Shirts ===
  Wardrobe.unlock_lvl('New Shirts', 13)
  Wardrobe.add('New Shirts', 'Body', 'Casual', 'Pink Flower Print', 'top', 'new_shirts/tops/pink_sleeveless_shirt', 6)
  Wardrobe.add('New Shirts', 'Body', 'Casual', 'Gray Polo', 'top', 'new_shirts/tops/short_sleeve_gray', 7)

  # === Referee Uniform ===
  Wardrobe.unlock_lvl('Referee Uniform', 14)
  Wardrobe.add('Referee Uniform', 'Body', 'Career', 'Referee Shirt', 'top', 'referee_uniform/tops/referee_t_shirt', 2)

  # === Golfer Outfit ===
  Wardrobe.unlock_lvl('Golfer Outfit', 15)
  Wardrobe.add('Golfer Outfit', 'Body', 'Sporty', 'Golf Shirt Blue', 'top', 'golfer_outfit/tops/golf_t_shirt_blue', 1)
  Wardrobe.add('Golfer Outfit', 'Body', 'Sporty', 'Golf Shirt Pink', 'top', 'golfer_outfit/tops/golf_t_shirt_pink', 2)
  Wardrobe.add('Golfer Outfit', 'Feet', 'Sporty', 'Golf Shoes', 'shoes', 'golfer_outfit/shoes/golf_shoe', 1)
  Wardrobe.add('Golfer Outfit', 'Head', 'Misc', 'Golf Hat', 'hat', 'golfer_outfit/hats/golf_hat_white', 1)
  Wardrobe.add('Golfer Outfit', 'Legs', 'Sporty', 'Golf Shorts', 'bottom', 'golfer_outfit/bottoms/golf_short', 1)

  # === Sports Equipment ===
  Wardrobe.unlock_lvl('Sports Equipment', 16)
  Wardrobe.add('Sports Equipment', 'Accessories', 'Hobbies', 'Football', 'prop', 'sports_equipment/props/american_football', 1)
  Wardrobe.add('Sports Equipment', 'Accessories', 'Hobbies', 'Baseball Bat', 'prop', 'sports_equipment/props/baseball_bat', 2)
  Wardrobe.add('Sports Equipment', 'Accessories', 'Hobbies', 'Basketball', 'prop', 'sports_equipment/props/basketball', 3)
  Wardrobe.add('Sports Equipment', 'Accessories', 'Hobbies', 'Golf Stick', 'prop', 'sports_equipment/props/golf_stick', 4)

  # === Policeman Uniform ===
  Wardrobe.unlock_lvl('Policeman Uniform', 17)
  Wardrobe.add('Policeman Uniform', 'Body', 'Career', 'Police Top', 'top', 'policeman_uniform/tops/police_top', 3)

  # === Farmer Outfit ===
  Wardrobe.unlock_lvl('Farmer Outfit', 18)
  Wardrobe.add('Farmer Outfit', 'Body', 'Career', 'Farmer Overalls', 'top', 'farmer_outfit/tops/farmer_tops', 4)

  # === Cool T-shirts ===
  Wardrobe.unlock_lvl('Cool T-shirts', 19)
  Wardrobe.add('Cool T-shirts', 'Body', 'Casual', 'Purple T', 'top', 'cool_t-shirts/tops/short_sleeve_purple', 8)
  Wardrobe.add('Cool T-shirts', 'Body', 'Casual', 'Gray T', 'top', 'cool_t-shirts/tops/short_sleeve_tattoo', 9)
  Wardrobe.add('Cool T-shirts', 'Body', 'Casual', 'Skinny Black T', 'top', 'cool_t-shirts/tops/skinny_black', 10)

  # === Hiker Gear ===
  Wardrobe.unlock_lvl('Hiker Gear', 20)
  Wardrobe.add('Hiker Gear', 'Body', 'Sporty', 'Hiker Top', 'top', 'hiker_gear/tops/hiking_jacket_red', 3)
  Wardrobe.add('Hiker Gear', 'Feet', 'Sporty', 'Hiking Shoes', 'shoes', 'hiker_gear/shoes/hiking_shoe', 2)

  # === Spanish Dancer Outfit ===
  Wardrobe.unlock_lvl('Spanish Dancer Outfit', 21)
  Wardrobe.add('Spanish Dancer Outfit', 'Body', 'Misc', 'Dancer Jacket', 'top', 'spanish_dancer outfit/tops/spanish_top', 2)
  Wardrobe.add('Spanish Dancer Outfit', 'Body', 'Misc', 'Dancer Blouse', 'top', 'spanish_dancer outfit/tops/spanish_women_red_top', 3)

  # === Instruments ===
  Wardrobe.unlock_lvl('Instruments', 22)
  Wardrobe.add('Instruments', 'Accessories', 'Hobbies', 'Bongo Drum', 'prop', 'instruments/props/bongo_drum', 5)
  Wardrobe.add('Instruments', 'Accessories', 'Hobbies', 'Acoustic Guitar', 'prop', 'instruments/props/guitar_brown', 6)
  Wardrobe.add('Instruments', 'Accessories', 'Hobbies', 'Saxophone', 'prop', 'instruments/props/saxophone', 7)

  # === Devil Costume ===
  Wardrobe.unlock_lvl('Devil Costume', 23)
  Wardrobe.add('Devil Costume', 'Accessories', 'Misc', 'Red Gloves', 'prop', 'devil_costume/glove/devil_glove', 4)
  Wardrobe.add('Devil Costume', 'Body', 'Misc', 'Devil Vest', 'top', 'devil_costume/tops/devil_shirt', 4)
  Wardrobe.add('Devil Costume', 'Body', 'Misc', 'Devil Dress', 'top', 'devil_costume/tops_misc/devil_short_dress', 5)
  Wardrobe.add('Devil Costume', 'Feet', 'Misc', 'Devil Boots', 'shoes', 'devil_costume/shoes/devil_boot', 1)
  Wardrobe.add('Devil Costume', 'Head', 'Misc', 'Devil Horns', 'hat', 'devil_costume/hats/devil_horns', 2)
  Wardrobe.add('Devil Costume', 'Legs', 'Misc', 'Devil Trousers', 'bottom', 'devil_costume/bottoms/trouser_devil', 2)

  # === Witch Costume ===
  Wardrobe.unlock_lvl('Witch Costume', 24)
  Wardrobe.add('Witch Costume', 'Accessories', 'Misc', 'Broom', 'prop', 'witch_costume/props/broom', 5)
  Wardrobe.add('Witch Costume', 'Body', 'Misc', 'Witch Dress', 'top', 'witch_costume/tops_misc/witch_black_dress', 6)

  # === Body Art ===
  Wardrobe.unlock_lvl('Body Art', 25)
  Wardrobe.add('Body Art', 'Accessories', 'Misc', 'Tattoo', 'prop', 'body_art/tattoo/tattoo', 6)
  Wardrobe.add('Body Art', 'Head', 'Misc', 'Mole', 'prop', 'body_art/facial_marks/mole', 3)
  Wardrobe.add('Body Art', 'Head', 'Misc', 'Red Lipstick', 'prop', 'body_art/makeup/makeup_red_lips', 4)
  Wardrobe.add('Body Art', 'Head', 'Misc', 'Santa Hat', 'hat', 'body_art/hats/santa_hat', 5)

  Admin.reset_rewards
end
