# Property of Levelfly. All rights reserved.
# This script is generated by script/create_wardrobe.rb on 2014-03-10

task :load_wardrobe => :environment do

  Reward.delete_all("target_type = 'wardrobe'")
  WardrobeItem.delete_all("depth = 2 and item_type <> 'head' and item_type <> 'hair' and item_type <> 'facial_hair'")
  Wardrobe.delete_all("name <> 'Basic'")

  # === Basic ===
  Wardrobe.unlock_lvl('Basic', 1)
  Wardrobe.add('Basic', 'Accessories', 'Jewelry', 'Hoop Earrings', 'earrings', 'basic/earrings/earring_large_ring', 0)
  Wardrobe.add('Basic', 'Accessories', 'Jewelry', 'Pearl Earrings', 'earrings', 'basic/earrings/earring_white', 1)
  Wardrobe.add('Basic', 'Accessories', 'Jewelry', 'Orange Earrings', 'earrings', 'basic/earrings/earring_orange', 2, 'Gold Earrings')
  Wardrobe.add('Basic', 'Accessories', 'Jewelry', 'Orange Necklace', 'necklace', 'basic/necklace/necklace_orange', 3, 'Gold Necklace')
  Wardrobe.add('Basic', 'Accessories', 'Hobbies', 'Guitar', 'prop', 'basic/props/guitar_black', 0, 'Electric Guitar')
  Wardrobe.add('Basic', 'Accessories', 'Misc', 'Gray Gloves', 'prop', 'basic/glove/glove_gray', 0)
  Wardrobe.add('Basic', 'Accessories', 'Misc', 'Pink Teddy Bear', 'prop', 'basic/props/pink_teddy', 1)
  Wardrobe.add('Basic', 'Accessories', 'Gadgets', 'Camera', 'prop', 'basic/props/camera', 0)
  Wardrobe.add('Basic', 'Accessories', 'Bags', 'Handbag', 'prop', 'basic/props/hand_bag', 0)
  Wardrobe.add('Basic', 'Accessories', 'Bags', 'Leather Bag', 'prop', 'basic/props/leather_bag', 1, 'Leather Briefcase')
  Wardrobe.add('Basic', 'Accessories', 'Bags', 'Messenger Bag', 'prop', 'basic/props/side_bag', 2)
  Wardrobe.add('Basic', 'Body', 'Casual', 'Black-T', 'top', 'basic/tops/black_t', 0, 'Black T')
  Wardrobe.add('Basic', 'Body', 'Casual', 'Blue Polo', 'top', 'basic/tops/polo_short_sleeve_blue', 1)
  Wardrobe.add('Basic', 'Body', 'Casual', 'Short Buttoned Blue Shirt', 'top', 'basic/tops/shirt_short_sleeve_cyan', 2, 'Blue Button Up')
  Wardrobe.add('Basic', 'Body', 'Casual', 'Short Buttoned Pink Shirt', 'top', 'basic/tops/shirt_short_sleeve_pink', 3, 'Pink Button Up')
  Wardrobe.add('Basic', 'Body', 'Career', 'Lab Coat', 'top', 'basic/tops/doctor_white_top', 0)
  Wardrobe.add('Basic', 'Body', 'Dressy', 'Black Tux', 'top', 'basic/tops_dressy/black_bow', 0)
  Wardrobe.add('Basic', 'Body', 'Dressy', 'Black Suit', 'top', 'basic/tops_dressy/dark_gray_tie', 1, 'Dark Gray Suit')
  Wardrobe.add('Basic', 'Body', 'Dressy', 'Black Dress', 'top', 'basic/tops_dressy/black_maroon_short_dress', 2, 'Black Maroon Dress')
  Wardrobe.add('Basic', 'Body', 'Dressy', 'Brown Dress', 'top', 'basic/tops_dressy/brown_dress', 3)
  Wardrobe.add('Basic', 'Body', 'Dressy', 'Orange Dress', 'top', 'basic/tops_dressy/orange_short_dress', 4)
  Wardrobe.add('Basic', 'Body', 'Dressy', 'Red Dress', 'top', 'basic/tops_dressy/red_long_dress', 5)
  Wardrobe.add('Basic', 'Body', 'Dressy', 'White Dress 3', 'top', 'basic/tops_dressy/white_short_dress', 6, 'White Dress 1')
  Wardrobe.add('Basic', 'Body', 'Dressy', 'White Dress 2', 'top', 'basic/tops_dressy/white_dress', 7)
  Wardrobe.add('Basic', 'Body', 'Dressy', 'White Dress', 'top', 'basic/tops_dressy/black_white_long_dress', 8, 'White Dress 3')
  Wardrobe.add('Basic', 'Body', 'Misc', 'Cowboy', 'top', 'basic/tops/cowboy_top_with_court', 0, 'Cowboy Jacket')
  Wardrobe.add('Basic', 'Body', 'Sporty', 'Football', 'top', 'basic/tops/american_football_top', 0, 'Football Top')
  Wardrobe.add('Basic', 'Body', 'Sporty', 'Baseball', 'top', 'basic/tops/baseball_t_shirt', 1, 'Baseball Top')
  Wardrobe.add('Basic', 'Feet', 'Career', 'Army', 'shoes', 'basic/shoes/army_boot', 0, 'Army Boots')
  Wardrobe.add('Basic', 'Feet', 'Sporty', 'Football', 'shoes', 'basic/shoes/american_football_shoe', 0, 'Football Cleats')
  Wardrobe.add('Basic', 'Feet', 'Sporty', 'Baseball', 'shoes', 'basic/shoes/baseball_shoe', 1, 'Baseball Cleats')
  Wardrobe.add('Basic', 'Feet', 'Misc', 'Cowboy', 'shoes', 'basic/shoes/cowboy_boot', 0, 'Cowboy Boots')
  Wardrobe.add('Basic', 'Feet', 'Misc', 'Purple Power', 'shoes', 'basic/shoes/purple_superhero_boot', 1, 'Black Boots')
  Wardrobe.add('Basic', 'Feet', 'Dressy', 'Black', 'shoes', 'basic/shoes/black_shoe', 0, 'Black Shoes')
  Wardrobe.add('Basic', 'Feet', 'Dressy', 'Black Heels', 'shoes', 'basic/shoes/black_heels', 1, 'Black Heels 2')
  Wardrobe.add('Basic', 'Feet', 'Dressy', 'White Heels', 'shoes', 'basic/shoes/white_heels_1', 2, 'White Heels 1')
  Wardrobe.add('Basic', 'Feet', 'Dressy', 'White Heels 2', 'shoes', 'basic/shoes/white_heels_2', 3)
  Wardrobe.add('Basic', 'Feet', 'Dressy', 'Red Heels', 'shoes', 'basic/shoes/red_heels', 4)
  Wardrobe.add('Basic', 'Feet', 'Dressy', 'Pink Heels', 'shoes', 'basic/shoes/shoe_pink', 5)
  Wardrobe.add('Basic', 'Feet', 'Casual', 'Brown Slippers', 'shoes', 'basic/shoes/slippers_brown', 0)
  Wardrobe.add('Basic', 'Feet', 'Casual', 'Purple Slippers', 'shoes', 'basic/shoes/slippers_purple', 1)
  Wardrobe.add('Basic', 'Feet', 'Casual', 'Grey Sneakers', 'shoes', 'basic/shoes/sneakers_gray', 2, 'Gray Sneakers')
  Wardrobe.add('Basic', 'Feet', 'Casual', 'Purple Sneakers', 'shoes', 'basic/shoes/sports_shoe_purple', 3)
  Wardrobe.add('Basic', 'Head', 'Face', 'Face 1', 'face', 'basic/face/asian_male', 0)
  Wardrobe.add('Basic', 'Head', 'Face', 'Face 2', 'face', 'basic/face/asian_female', 1)
  Wardrobe.add('Basic', 'Head', 'Face', 'Face 3', 'face', 'basic/face/chinese_male', 2)
  Wardrobe.add('Basic', 'Head', 'Face', 'Face 4', 'face', 'basic/face/chinese_female', 3)
  Wardrobe.add('Basic', 'Head', 'Face', 'Face 5', 'face', 'basic/face/african_male', 4)
  Wardrobe.add('Basic', 'Head', 'Face', 'Face 6', 'face', 'basic/face/african_female', 5)
  Wardrobe.add('Basic', 'Head', 'Face', 'Face 7', 'face', 'basic/face/latin_male', 6)
  Wardrobe.add('Basic', 'Head', 'Face', 'Face 8', 'face', 'basic/face/latin_female', 7)
  Wardrobe.add('Basic', 'Head', 'Face', 'Face 9', 'face', 'basic/expression/angry_1', 8)
  Wardrobe.add('Basic', 'Head', 'Face', 'Face 10', 'face', 'basic/expression/angry_2', 9)
  Wardrobe.add('Basic', 'Head', 'Face', 'Face 11', 'face', 'basic/expression/angry_3', 10)
  Wardrobe.add('Basic', 'Head', 'Face', 'Face 12', 'face', 'basic/expression/angry_4', 11)
  Wardrobe.add('Basic', 'Head', 'Face', 'Face 13', 'face', 'basic/expression/smile_1', 12)
  Wardrobe.add('Basic', 'Head', 'Face', 'Face 14', 'face', 'basic/expression/smile_2', 13)
  Wardrobe.add('Basic', 'Head', 'Face', 'Face 15', 'face', 'basic/expression/smile_3', 14)
  Wardrobe.add('Basic', 'Head', 'Face', 'Face 16', 'face', 'basic/expression/smile_4', 15)
  Wardrobe.add('Basic', 'Head', 'Face', 'Face 17', 'face', 'basic/expression/winking_1', 16)
  Wardrobe.add('Basic', 'Head', 'Face', 'Face 18', 'face', 'basic/expression/winking_2', 17)
  Wardrobe.add('Basic', 'Head', 'Face', 'Face 19', 'face', 'basic/expression/winking_3', 18)
  Wardrobe.add('Basic', 'Head', 'Face', 'Face 20', 'face', 'basic/expression/winking_4', 19)
  Wardrobe.add('Basic', 'Head', 'Misc', 'Black Cap', 'hat', 'basic/hats/hat_red_black', 0)
  Wardrobe.add('Basic', 'Legs', 'Sporty', 'Football', 'bottom', 'basic/bottoms/american_football_pant', 0, 'Football Bottom')
  Wardrobe.add('Basic', 'Legs', 'Sporty', 'Baseball', 'bottom', 'basic/bottoms/baseball_pant', 1, 'Baseball Bottom')
  Wardrobe.add('Basic', 'Legs', 'Misc', 'Purple Power', 'bottom', 'basic/bottoms/purple_superhero_bottom', 0, 'Purple Tights')
  Wardrobe.add('Basic', 'Legs', 'Casual', 'Black Skinny Jeans', 'bottom', 'basic/bottoms/black_tight_jean', 0)
  Wardrobe.add('Basic', 'Legs', 'Casual', 'Long Denim', 'bottom', 'basic/bottoms/trousers_long_denim_blue', 1, 'Blue Jeans')
  Wardrobe.add('Basic', 'Legs', 'Casual', 'Short Denim', 'bottom', 'basic/bottoms/trousers_short_denim_blue', 2, 'Denim Shorts')
  Wardrobe.add('Basic', 'Legs', 'Career', 'Army', 'bottom', 'basic/bottoms/trouser_army', 0, 'Army Fatigues')
  Wardrobe.add('Basic', 'Legs', 'Dressy', 'Grey Trousers', 'bottom', 'basic/bottoms/gray_brown_long_trouser', 0, 'Gray Trousers')
  Wardrobe.add('Basic', 'Legs', 'Dressy', 'Short Brown Skirt', 'bottom', 'basic/bottoms/skirt_short_brown', 1)
  Wardrobe.add('Basic', 'Legs', 'Dressy', 'Short Pink Skirt', 'bottom', 'basic/bottoms/skirt_short_pink', 2)

  # === BMCC T-shirts ===
  Wardrobe.unlock_lvl('BMCC T-shirts', 2)
  Wardrobe.add('BMCC T-shirts', 'Body', 'Casual', 'BMCC 1', 'top', 'bmcc_t-shirts/tops/bmcc_blue', 4)
  Wardrobe.add('BMCC T-shirts', 'Body', 'Casual', 'BMCC 2', 'top', 'bmcc_t-shirts/tops/bmcc_light_gray', 5)
  Wardrobe.add('BMCC T-shirts', 'Body', 'Casual', 'BMCC 3', 'top', 'bmcc_t-shirts/tops/bmcc_small_logo', 6)
  Wardrobe.add('BMCC T-shirts', 'Body', 'Casual', 'BMCC 4', 'top', 'bmcc_t-shirts/tops/bmcc_yellow_small_logo', 7)

  # === Basketball Uniform ===
  Wardrobe.unlock_lvl('Basketball Uniform', 3)
  Wardrobe.add('Basketball Uniform', 'Body', 'Sporty', 'Basketball Jersey', 'top', 'basketball_uniform/tops/basketball_t_shirt', 2)
  Wardrobe.add('Basketball Uniform', 'Feet', 'Sporty', 'Basketball Shoes', 'shoes', 'basketball_uniform/shoes/basketball_shoe', 2)
  Wardrobe.add('Basketball Uniform', 'Legs', 'Sporty', 'Basketball Shorts', 'bottom', 'basketball_uniform/bottoms/basketball_short', 2)

  # === Urban Chic Accessories ===
  Wardrobe.unlock_lvl('Urban Chic Accessories', 4)
  Wardrobe.add('Urban Chic Accessories', 'Accessories', 'Jewelry', 'Nosestud', 'earrings', 'urban_chic accessories/earrings/nose_stud', 4, 'Nose Stud')
  Wardrobe.add('Urban Chic Accessories', 'Accessories', 'Misc', 'Sunglasses', 'prop', 'urban_chic accessories/glasses/shade_black', 2)

  # === Superhero Costume ===
  Wardrobe.unlock_lvl('Superhero Costume', 5)
  Wardrobe.add('Superhero Costume', 'Body', 'Misc', 'Purple Power', 'top', 'superhero_costume/tops/purple_superhero_top', 1, 'Superhero')

  # === Cowboy Outfit ===
  Wardrobe.unlock_lvl('Cowboy Outfit', 6)
  Wardrobe.add('Cowboy Outfit', 'Body', 'Misc', 'Cowboy Vest', 'top', 'cowboy_outfit/tops/cowboy_top_without_court', 2)
  Wardrobe.add('Cowboy Outfit', 'Head', 'Misc', 'Cowboy', 'hat', 'cowboy_outfit/hats/cowboy_hat', 1, 'Cowboy Hat')
  Wardrobe.add('Cowboy Outfit', 'Legs', 'Misc', 'Cowboy Chaps', 'bottom', 'cowboy_outfit/bottoms/cowboy_bottom', 1)

  # === Skater Accessories ===
  Wardrobe.unlock_lvl('Skater Accessories', 7)
  Wardrobe.add('Skater Accessories', 'Accessories', 'Hobbies', 'Skateboard', 'prop', 'skater_accessories/props/skateboard', 1)
  Wardrobe.add('Skater Accessories', 'Accessories', 'Gadgets', 'Headphones', 'prop', 'skater_accessories/props/headphone', 1)

  # === Doctor Accessories ===
  Wardrobe.unlock_lvl('Doctor Accessories', 8)
  Wardrobe.add('Doctor Accessories', 'Accessories', 'Misc', 'Stethoscope', 'prop', 'doctor_accessories/props/stethoscope', 3)

  # === Business Outfits ===
  Wardrobe.unlock_lvl('Business Outfits', 9)
  Wardrobe.add('Business Outfits', 'Body', 'Dressy', 'Red Tie', 'top', 'business_outfits/tops/red_tie_shirt_long_sleeve', 9)
  Wardrobe.add('Business Outfits', 'Body', 'Dressy', 'Argyle Sweater', 'top', 'business_outfits/tops/shirt_long_sleeve_with_jacket', 10)
  Wardrobe.add('Business Outfits', 'Body', 'Dressy', 'Blue Tie', 'top', 'business_outfits/tops/tie_shirt_long_sleeve_yellow', 11)
  Wardrobe.add('Business Outfits', 'Legs', 'Dressy', 'Brown Trousers', 'bottom', 'business_outfits/bottoms/trousers_long_brown', 3)

  # === Army Uniform ===
  Wardrobe.unlock_lvl('Army Uniform', 10)
  Wardrobe.add('Army Uniform', 'Body', 'Career', 'Army Shirt 1', 'top', 'army_uniform/tops/shirt_army', 1)
  Wardrobe.add('Army Uniform', 'Body', 'Career', 'Army Shirt 2', 'top', 'army_uniform/tops/t_shirt_army', 2)

  # === New Jewelry ===
  Wardrobe.unlock_lvl('New Jewelry', 11)
  Wardrobe.add('New Jewelry', 'Accessories', 'Jewelry', 'Sapphire Earrings', 'earrings', 'new_jewelry/earrings/earring_blue', 5)
  Wardrobe.add('New Jewelry', 'Accessories', 'Jewelry', 'Ruby Earrings', 'earrings', 'new_jewelry/earrings/earring_red', 6)
  Wardrobe.add('New Jewelry', 'Accessories', 'Jewelry', 'Silver Drop Earrings', 'earrings', 'new_jewelry/earrings/earring_silver_1', 7)
  Wardrobe.add('New Jewelry', 'Accessories', 'Jewelry', 'Silver Stud Earrings', 'earrings', 'new_jewelry/earrings/earring_silver_2', 8)
  Wardrobe.add('New Jewelry', 'Accessories', 'Jewelry', 'Silver Necklace 1', 'necklace', 'new_jewelry/necklace/necklace_silver_1', 9)
  Wardrobe.add('New Jewelry', 'Accessories', 'Jewelry', 'Silver Necklace 2', 'necklace', 'new_jewelry/necklace/necklace_silver_2', 10)
  Wardrobe.add('New Jewelry', 'Accessories', 'Jewelry', 'Diamond Necklace 1', 'necklace', 'new_jewelry/necklace/necklace_diamond_1', 11)
  Wardrobe.add('New Jewelry', 'Accessories', 'Jewelry', 'Diamond Necklace 2', 'necklace', 'new_jewelry/necklace/necklace_diamond_2', 12)

  # === Pirate Costume ===
  Wardrobe.unlock_lvl('Pirate Costume', 12)
  Wardrobe.add('Pirate Costume', 'Legs', 'Misc', 'Pirate Bottom', 'bottom', 'pirate_costume/bottoms/pirate_bottom', 2)
  Wardrobe.add('Pirate Costume', 'Feet', 'Misc', 'Pirate Boots', 'shoes', 'pirate_costume/shoes/pirate_boot', 2)
  Wardrobe.add('Pirate Costume', 'Body', 'Misc', 'Pirate Top', 'top', 'pirate_costume/tops/pirate_top', 3)
  Wardrobe.add('Pirate Costume', 'Head', 'Misc', 'Pirate Hat 2', 'hat', 'pirate_costume/hats/pirate_hat', 2)

  # === New Shirts ===
  Wardrobe.unlock_lvl('New Shirts', 13)
  Wardrobe.add('New Shirts', 'Body', 'Casual', 'Pink Flower Print', 'top', 'new_shirts/tops/pink_sleeveless_shirt', 8)
  Wardrobe.add('New Shirts', 'Body', 'Casual', 'Gray Polo', 'top', 'new_shirts/tops/short_sleeve_gray', 9)

  # === Referee Uniform ===
  Wardrobe.unlock_lvl('Referee Uniform', 14)
  Wardrobe.add('Referee Uniform', 'Body', 'Career', 'Referee Shirt', 'top', 'referee_uniform/tops/referee_t_shirt', 3)

  # === Golfer Outfit ===
  Wardrobe.unlock_lvl('Golfer Outfit', 15)
  Wardrobe.add('Golfer Outfit', 'Body', 'Sporty', 'Golf Shirt Blue', 'top', 'golfer_outfit/tops/golf_t_shirt_blue', 3)
  Wardrobe.add('Golfer Outfit', 'Body', 'Sporty', 'Golf Shirt Pink', 'top', 'golfer_outfit/tops/golf_t_shirt_pink', 4)
  Wardrobe.add('Golfer Outfit', 'Feet', 'Sporty', 'Golf Shoes', 'shoes', 'golfer_outfit/shoes/golf_shoe', 3)
  Wardrobe.add('Golfer Outfit', 'Head', 'Misc', 'Golf Hat', 'hat', 'golfer_outfit/hats/golf_hat_white', 3)
  Wardrobe.add('Golfer Outfit', 'Legs', 'Sporty', 'Golf Shorts', 'bottom', 'golfer_outfit/bottoms/golf_short', 3)

  # === Sports Equipment ===
  Wardrobe.unlock_lvl('Sports Equipment', 16)
  Wardrobe.add('Sports Equipment', 'Accessories', 'Hobbies', 'Football', 'prop', 'sports_equipment/props/american_football', 2)
  Wardrobe.add('Sports Equipment', 'Accessories', 'Hobbies', 'Baseball Bat', 'prop', 'sports_equipment/props/baseball_bat', 3)
  Wardrobe.add('Sports Equipment', 'Accessories', 'Hobbies', 'Basketball', 'prop', 'sports_equipment/props/basketball', 4)
  Wardrobe.add('Sports Equipment', 'Accessories', 'Hobbies', 'Golf Stick', 'prop', 'sports_equipment/props/golf_stick', 5)

  # === Policeman Uniform ===
  Wardrobe.unlock_lvl('Policeman Uniform', 17)
  Wardrobe.add('Policeman Uniform', 'Body', 'Career', 'Police Top', 'top', 'policeman_uniform/tops/police_top', 4)

  # === Farmer Outfit ===
  Wardrobe.unlock_lvl('Farmer Outfit', 18)
  Wardrobe.add('Farmer Outfit', 'Body', 'Career', 'Farmer Overalls', 'top', 'farmer_outfit/tops/farmer_tops', 5)

  # === Cool T-shirts ===
  Wardrobe.unlock_lvl('Cool T-shirts', 19)
  Wardrobe.add('Cool T-shirts', 'Body', 'Casual', 'Purple T', 'top', 'cool_t-shirts/tops/short_sleeve_purple', 10)
  Wardrobe.add('Cool T-shirts', 'Body', 'Casual', 'Gray T', 'top', 'cool_t-shirts/tops/short_sleeve_tattoo', 11)
  Wardrobe.add('Cool T-shirts', 'Body', 'Casual', 'Skinny Black T', 'top', 'cool_t-shirts/tops/skinny_black', 12)

  # === Hiker Gear ===
  Wardrobe.unlock_lvl('Hiker Gear', 20)
  Wardrobe.add('Hiker Gear', 'Body', 'Sporty', 'Hiker Top', 'top', 'hiker_gear/tops/hiking_jacket_red', 5)
  Wardrobe.add('Hiker Gear', 'Feet', 'Sporty', 'Hiking Shoes', 'shoes', 'hiker_gear/shoes/hiking_shoe', 4)

  # === Spanish Dancer Outfit ===
  Wardrobe.unlock_lvl('Spanish Dancer Outfit', 21)
  Wardrobe.add('Spanish Dancer Outfit', 'Body', 'Misc', 'Dancer Jacket', 'top', 'spanish_dancer outfit/tops/spanish_top', 4)
  Wardrobe.add('Spanish Dancer Outfit', 'Body', 'Misc', 'Dancer Blouse', 'top', 'spanish_dancer outfit/tops/spanish_women_red_top', 5)

  # === Instruments ===
  Wardrobe.unlock_lvl('Instruments', 22)
  Wardrobe.add('Instruments', 'Accessories', 'Hobbies', 'Bongo Drum', 'prop', 'instruments/props/bongo_drum', 6)
  Wardrobe.add('Instruments', 'Accessories', 'Hobbies', 'Acoustic Guitar', 'prop', 'instruments/props/guitar_brown', 7)
  Wardrobe.add('Instruments', 'Accessories', 'Hobbies', 'Saxophone', 'prop', 'instruments/props/saxophone', 8)

  # === Devil Costume ===
  Wardrobe.unlock_lvl('Devil Costume', 23)
  Wardrobe.add('Devil Costume', 'Accessories', 'Misc', 'Red Gloves', 'prop', 'devil_costume/glove/devil_glove', 4)
  Wardrobe.add('Devil Costume', 'Accessories', 'Misc', 'Pitchfork', 'prop', 'devil_costume/props/pitchfork', 5)
  Wardrobe.add('Devil Costume', 'Body', 'Misc', 'Devil Vest', 'top', 'devil_costume/tops/devil_shirt', 6)
  Wardrobe.add('Devil Costume', 'Body', 'Misc', 'Devil Dress', 'top', 'devil_costume/tops_misc/devil_short_dress', 7)
  Wardrobe.add('Devil Costume', 'Feet', 'Misc', 'Devil Boots', 'shoes', 'devil_costume/shoes/devil_boot', 3)
  Wardrobe.add('Devil Costume', 'Head', 'Misc', 'Devil Horns', 'hat', 'devil_costume/hats/devil_horns', 4)
  Wardrobe.add('Devil Costume', 'Legs', 'Misc', 'Devil Trousers', 'bottom', 'devil_costume/bottoms/trouser_devil', 3)

  # === Witch Costume ===
  Wardrobe.unlock_lvl('Witch Costume', 24)
  Wardrobe.add('Witch Costume', 'Accessories', 'Misc', 'Broom', 'prop', 'witch_costume/props/broom', 6)
  Wardrobe.add('Witch Costume', 'Body', 'Misc', 'Witch Dress', 'top', 'witch_costume/tops_misc/witch_black_dress', 8)

  # === Body Art ===
  Wardrobe.unlock_lvl('Body Art', 25)
  Wardrobe.add('Body Art', 'Accessories', 'Misc', 'Tattoo', 'prop', 'body_art/tattoo/tattoo', 7)
  Wardrobe.add('Body Art', 'Head', 'Misc', 'Mole', 'prop', 'body_art/facial_marks/mole', 5)
  Wardrobe.add('Body Art', 'Head', 'Misc', 'Red Lipstick', 'prop', 'body_art/makeup/makeup_red_lips', 6)

  # === Santa Costume ===
  Wardrobe.unlock_lvl('Santa Costume', 26)
  Wardrobe.add('Santa Costume', 'Body', 'Misc', 'Santa', 'top', 'santa_costume/tops/santa_top', 9, 'Santa Top')
  Wardrobe.add('Santa Costume', 'Head', 'Misc', 'Santa Hat', 'hat', 'santa_costume/hats/santa_hat', 7)
  Wardrobe.add('Santa Costume', 'Legs', 'Misc', 'Santa', 'bottom', 'santa_costume/bottoms/santa_trouser', 4, 'Santa Bottom')

  Admin.reset_rewards
end
