---
kind: pipeline
name: publish docker image
steps:
  - name: build and publish
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: neuronicgames/levelfly
      tags: ${DRONE_COMMIT_BRANCH}
