---
# NOTE: For local development! See https://git.coopcloud.tech/coop-cloud/levelfly for a production config

x-environment:
  &default-env
    - NEW_RELIC_AGENT_ENABLED=false
    - RAILS_ENV=development
    - DATABASE_URL=postgresql://levelfly:password@db:5432/levelfly
    - DATABASE_URL_TEST=postgresql://levelfly:password@db:5432/levelfly_test
    - DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL=true
    - URL=http://localhost:3000
    - LOG_LEVEL=debug
    - SMTP_HOST=mail
    - SMTP_PORT=1025

services:
  app:
    build:
      context: .
      target: dev
    image: neuronicgames/levelfly
    volumes:
      - ./:/var/app:z
      - levelfly_storage:/var/app/storage
    environment: *default-env
    depends_on:
      - db
    ports:
      - 3000:3000
  jobs:
    build: .
    image: neuronicgames/levelfly
    command: bundle exec rake jobs:work
    volumes:
      - ./:/var/app:z
      - levelfly_storage:/var/app/storage
    environment: *default-env
    depends_on:
      - app
      - db
  db:
    restart: always
    image: postgres:9.6-alpine
    ports:
      - 55432:5432
    environment: 
      POSTGRES_DB: levelfly
      POSTGRES_USER: levelfly
      POSTGRES_PASSWORD: password
    shm_size: 256mb
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "levelfly"]
    volumes:
      - postgres_data:/var/lib/postgresql/data
  mail:
    image: dockage/mailcatcher:0.9.0
    ports:
      - 1025:1025
      - 1080:1080
                
networks:
  internal_network:
    internal: true

volumes:
  postgres_data:
  levelfly_storage:
