# Application configuration that is loaded as environment variables
# This is only loaded in the development environment from development.rb
# In production, the variables are set by Heroku / Docker Swarm

MAILER_DEFAULT_URL: localhost:3000
# For outgoing emails - edit config/environments/development.rb
#SMTP_PASSWORD: AAAAAAAAAAAAAAAAAAAAAA
#SMTP_USER: user@example.com
#SMTP_HOST: smtp.example.com
#SMTP_PORT: 587
#SMTP_DOMAIN: example.com

# For notifications
PUSHER_SOCKET_URL: ws://ws.pusherapp.com/app/ID
PUSHER_URL: https://ID:KEY@api.pusherapp.com/apps/APP

S3_KEY: AAAAAAAAAAAAAAAAAAAA
S3_PATH: my-s3-account.s3.amazonaws.com/my-box-name
S3_PROTOCOL: https
S3_SECRET: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

# Used to prefix URLs (e.g. reference to images in emails)
URL: http://localhost:3000

SMTP_DOMAIN: localhost

SUPPORT_EMAIL: test@example.com
