# Application configuration that is loaded as environment variables
# This is only loaded in the development environment from development.rb
# In production, the variables are set by Heroku / Docker Swarm

# TODO: Maybe drop this file? Development settings might be different depending on Docker vs bare-metal, probably best to set everything in env vars

MAILER_DEFAULT_URL: localhost:3000
# For outgoing emails - edit config/environments/development.rb
#SMTP_PASSWORD: AAAAAAAAAAAAAAAAAAAAAA
#SMTP_USER: user@example.com
#SMTP_HOST: smtp.example.com
#SMTP_PORT: 587
#SMTP_DOMAIN: example.com

# Used to prefix URLs (e.g. reference to images in emails)
URL: http://localhost:3000

SMTP_DOMAIN: localhost

SUPPORT_EMAIL: test@example.com
